attack.h File Reference
#include "../defs.h"
Functions
bool isSquareAttacked (int sq, int side, const S_BOARD *pos)
Determines if a given square is attacked by a given side.
Variables
const int knightDirection [8]
Knight movement directions in 120-square board representation.
const int rookDirection [4]
Rook movement directions in 120-square board representation.
const int bishopDirection [4]
Bishop movement directions in 120-square board representation.
const int kingDirection [8]
King movement directions in 120-square board representation.
Function Documentation
isSquareAttacked()
bool isSquareAttacked (int sq, int side, const S_BOARD * pos) [extern]
Determines if a given square is attacked by a given side.
Parameters
sq Square index (120-based representation).
side Side to check for attacks (WHITE or BLACK).
pos Pointer to the current board state.
Returns
true if the square is attacked by the given side, false otherwise.
Definition at line 9 of file attack.cpp.
References ASSERT, bishopDirection, bP, EMPTY, isBoardStateValid(), IsBQ, IsKi, IsKn, IsRQ, kingDirection, knightDirection, OFFBOARD, PceValidEmptyOffbrd(), pieceColor, S_BOARD::pieces, rookDirection, SideValid(), SqIs120(), SqOnBoard(), WHITE, and wP.
Referenced by generateAllMoves(), makeMove(), and makeNullMove().
Variable Documentation
bishopDirection
const int bishopDirection[4] [extern]
Bishop movement directions in 120-square board representation.
Definition at line 6 of file attack.cpp.
Referenced by isSquareAttacked().
kingDirection
const int kingDirection[8] [extern]
King movement directions in 120-square board representation.
Definition at line 7 of file attack.cpp.
Referenced by isSquareAttacked().
knightDirection
const int knightDirection[8] [extern]
Knight movement directions in 120-square board representation.
Definition at line 4 of file attack.cpp.
Referenced by isSquareAttacked().
rookDirection
const int rookDirection[4] [extern]
Rook movement directions in 120-square board representation.
Definition at line 5 of file attack.cpp.
Referenced by isSquareAttacked().