misc.cpp File Reference
#include "misc.h"
#include <chrono>
#include <cstdio>
#include <cstring>
#include <sys/select.h>
#include <sys/time.h>
#include <unistd.h>
Functions
int GetTimeMs ()
int InputWaiting ()
void ReadInput (S_SEARCHINFO *info)
Function Documentation
GetTimeMs()
int GetTimeMs ()
Definition at line 17 of file misc.cpp.
Referenced by PerftTest().
InputWaiting()
int InputWaiting ()
Definition at line 26 of file misc.cpp.
Referenced by ReadInput().
ReadInput()
void ReadInput (S_SEARCHINFO * info)
Definition at line 77 of file misc.cpp.
References InputWaiting(), S_SEARCHINFO::quit, S_SEARCHINFO::stopped, and TRUE.