misc.h File Reference
#include "../defs.h"
Functions
int GetTimeMs ()
int InputWaiting ()
void ReadInput (S_SEARCHINFO *info)
Function Documentation
GetTimeMs()
int GetTimeMs () [extern]
Definition at line 17 of file misc.cpp.
Referenced by PerftTest().
InputWaiting()
int InputWaiting () [extern]
Definition at line 26 of file misc.cpp.
Referenced by ReadInput().
ReadInput()
void ReadInput (S_SEARCHINFO * info) [extern]
Definition at line 77 of file misc.cpp.
References InputWaiting(), S_SEARCHINFO::quit, S_SEARCHINFO::stopped, and TRUE.