perft.h File Reference
#include "../defs.h"
#include "../board/board.h"
Functions
void Perft (int depth, S_BOARD *pos)
Runs a perft search from a given board state.
void PerftTest (int depth, S_BOARD *pos)
Executes a perft test and prints move breakdown and timing.
Variables
long leafNodes
Global counter for leaf nodes visited during perft.
Function Documentation
Perft()
void Perft (int depth, S_BOARD * pos) [extern]
Runs a perft search from a given board state.
Parameters
depth The depth to search.
pos Pointer to the board state.
Definition at line 11 of file perft.cpp.
References ASSERT, S_MOVELIST::count, generateAllMoves(), isBoardStateValid(), leafNodes, makeMove(), S_MOVE::move, S_MOVELIST::moves, Perft(), and takeMove().
Referenced by Perft(), and PerftTest().
PerftTest()
void PerftTest (int depth, S_BOARD * pos) [extern]
Executes a perft test and prints move breakdown and timing.
Parameters
depth The depth to search.
pos Pointer to the board state.
Definition at line 32 of file perft.cpp.
References ASSERT, S_MOVELIST::count, generateAllMoves(), GetTimeMs(), isBoardStateValid(), leafNodes, makeMove(), S_MOVE::move, S_MOVELIST::moves, moveToString(), Perft(), printBoardState(), and takeMove().
Referenced by main().
Variable Documentation
leafNodes
long leafNodes [extern]
Global counter for leaf nodes visited during perft.
Definition at line 9 of file perft.cpp.
Referenced by Perft(), and PerftTest().